---
platform: windows

params:
  ADMIN_USER:
  ADMIN_PASSWORD:

inputs:
- name: cli-acceptance-tests
  path: gopath/src/github.com/cloudfoundry/cli-acceptance-tests
- name: cf-cli-binaries
- name: bosh-lite-lock
- name: cli

run:
  path: cli/ci/tasks/gats-windows.bat
